### ISSUE TITLE
Build out HTML Frame

### ISSUE THREAD

**Issue by SamGulinello** [SamGulinello/TraderPy#18]

**Comment by Mount-Blanc** [comment]
Hello, I would to work on this issue. By HTML frame, do you mean the basic HTML boilerplate?

**Comment by SamGulinello** [comment]
With the most recent push I made to the main branch I added an index.html as well as some javascript to populate the data async.  The HTML creates a very basic UI and could use a lot of improvement as well as further development. I envision the application to be a single page and asynchronous and act as a dashboard of the application data. I am very open-minded on what can be done with it.

**Comment by SamGulinello** [comment]
Right now the documentation is just a few ReadMe files in the repo. It would be great to have a website that displayed the markdown as well as provided simple navigation between the files and was easy to update as more documentation is written. It's not necessarily a boilerplate but instead just some wrapping for the markdown.
